resolver: lts-20.18

packages:
- .
- ./duo-lang-parser
- ./duo-lang-renamer
- ./duo-lang-desugaring

extra-deps:
- diagnose-2.2.0
- git: https://github.com/solidsnack/wcwidth.git
  commit: 747297319f0dd0c8e8f72b7de4fbf52aad73d5b0

system-ghc: true

