[book]
title = "DualSub - Documentation"
authors = ["David Binder"]
description = "Documentation of the DualSub language"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
mathjax-support = true
git-repository-url = "https://github.com/ps-tuebingen/dualsub"
edit-url-template = "https://github.com/ps-tuebingen/dualsub/edit/main/docs/{path}"
