[book]
title = "Duo - Documentation"
authors = ["David Binder"]
description = "Documentation of the Duo language"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
mathjax-support = true
git-repository-url = "https://github.com/ps-tuebingen/duo-lang"
edit-url-template = "https://github.com/ps-tuebingen/duo-lang/edit/main/docs/{path}"
