name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - 'docs/**'

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        stack: ["2.7.5"]
        ghc: ["9.0.2"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1.1.4
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: freckle/stack-cache-action@v2.0.8
      with:
        prefix: ${{ runner.os }}-${{ matrix.ghc }}

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc

