name: Publish Docs on GH Page
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH

    - name: Create mdBook page
      run: mdbook build
      working-directory: docs

    - uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
          branch: gh-pages
          folder: docs/book