name: vscode-plugin
on:
  push:
    branches:
      - main
    paths:
      - 'vscode-plugin/**'
      - '.github/workflows/vscode-plugin.yml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'vscode-plugin/**'
      - '.github/workflows/vscode-plugin.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./vscode-plugin
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ${{env.working-directory}}
      - uses: lannonbr/vsce-action@master
        working-directory: ${{env.working-directory}}
        with:
          args: "package"
